apiVersion: skaffold/v4beta1
kind: Config
manifests:
  rawYaml:
    - k8s-manifests/namespace.yaml
    - k8s-manifests/deployment.yaml
    - k8s-manifests/service.yaml
    - k8s-manifests/ingress.yaml
    - k8s-manifests/autoscaler.yaml
deploy:
  kubectl:
    flags:
      apply:
        - --server-side # Avoid the "Too long: must have at most 262144 bytes" problem
  tolerateFailuresUntilDeadline: true # Fixes startup timeouts
